---
# Включаем маршрутизацию транзитных пакетов
- name: Setup forward net.ipv4.conf.all.forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.forwarding
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Setup forward net.ipv4.ip_forward
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes