---
- name: Configuring daemons
  template:
    backup: yes
    src: daemons.j2
    dest: /etc/frr/daemons
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - reload frr
    - start frr

- name: Configuring FRR
  template:
    backup: yes
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - reload frr
    - start frr