# code: language=ansible
---
- hosts: all
  become: true
  tasks:
  - name: Set timezone to {{ timezone }}
    command: timedatectl set-timezone {{ timezone }}
    vars:
      timezone: Europe/Moscow
  roles:
    - role: system-tuning
    - role: install-depend

- name: Prepare router1
  hosts: router1
  become: true
  roles:
    - role: vlan-setup
      vlan_iface:
        vlan10:
          vlanipv4: 10.0.12.1/30
          vlanid: 10
          vlandev: eth1
        vlan11:
          vlanipv4: 10.0.10.1/30
          vlanid: 11
          vlandev: eth1
    - role: frr-instance
      frr_interfaces:
        vlan11:
          ip: 10.0.10.1/30
          description: r1-r2
          other:
            - "ip ospf mtu-ignore"
            - "ip ospf cost 45"
            - "ip ospf hello-interval 10"
            - "ip ospf dead-interval 30"
        vlan10:
          ip: 10.0.12.1/30
          description: r1-r3
          other:
            - "ip ospf mtu-ignore"
            - "ip ospf cost 45"
            - "ip ospf hello-interval 10"
            - "ip ospf dead-interval 30"
        eth2:
          ip: 192.168.10.1/24
          description: net_router1
          other:
            - "ip ospf mtu-ignore"
            - "ip ospf cost 45"
            - "ip ospf hello-interval 10"
            - "ip ospf dead-interval 30"
      frr_ospf:
        areas:
          0:
            networks:
              - 10.0.10.0/30
              - 10.0.12.0/30
              - 192.168.10.0/24

- name: Prepare router2
  hosts: router2
  become: true
  roles:
    - role: vlan-setup
      vlan_iface:
        vlan11:
          vlanid: 11
          vlandev: eth1
        vlan12:
          vlanid: 12
          vlandev: eth1
    - role: frr-instance
      frr_interfaces:
        vlan11:
          ip: 10.0.10.2/30
          description: r1-r2
          other:
            - "ip ospf mtu-ignore"
            - "ip ospf cost 45"
            - "ip ospf hello-interval 10"
            - "ip ospf dead-interval 30"
        vlan12:
          ip: 10.0.11.2/30
          description: r2-r3
          other:
            - "ip ospf mtu-ignore"
            - "ip ospf cost 45"
            - "ip ospf hello-interval 10"
            - "ip ospf dead-interval 30"
        eth2:
          ip: 192.168.20.1/24
          description: net_router2
          other:
            - "ip ospf mtu-ignore"
            - "ip ospf cost 45"
            - "ip ospf hello-interval 10"
            - "ip ospf dead-interval 30"
      frr_ospf:
        areas:
          0:
            networks:
              - 10.0.10.0/30
              - 10.0.11.0/30
              - 192.168.20.0/24

- name: Prepare router3
  hosts: router3
  become: true
  roles:
    - role: vlan-setup
      vlan_iface:
        vlan10:
          vlanid: 10
          vlandev: eth1
        vlan12:
          vlanid: 12
          vlandev: eth1
    - role: frr-instance
      frr_interfaces:
        vlan12:
          ip: 10.0.11.1/30
          description: r2-r3
          other:
            - "ip ospf mtu-ignore"
            - "ip ospf cost 45"
            - "ip ospf hello-interval 10"
            - "ip ospf dead-interval 30"
        vlan10:
          ip: 10.0.12.2/30
          description: r1-r3
          other:
            - "ip ospf mtu-ignore"
            - "ip ospf cost 45"
            - "ip ospf hello-interval 10"
            - "ip ospf dead-interval 30"
        eth2:
          ip: 192.168.30.1/24
          description: net_router3
          other:
            - "ip ospf mtu-ignore"
            - "ip ospf cost 45"
            - "ip ospf hello-interval 10"
            - "ip ospf dead-interval 30"
      frr_ospf:
        areas:
          0:
            networks:
              - 10.0.11.0/30
              - 10.0.12.0/30
              - 192.168.30.0/24